#  Guilherme Costa Vieira               Nº USP: 9790930
#  Victor Chiaradia Gramuglia Araujo    Nº USP: 9793756

CFLAGS = -Wall -Werror -g -pthread
CC = gcc

ep2 : simulator2.c track.c
		$(CC) $? $(CFLAGS) -o $@ -I.
